### ISSUE TITLE
Typo in utility name

### ISSUE THREAD

**Issue by asheshv** [EnterpriseDB/cloud-utilities#1]
https://github.com/EnterpriseDB/cloud-utilities/blob/ff8896f5fa9bfaddc61ff3e1e9fc6595dce5caf8/azure/resource-quotas.sh#L7

Name of utility in usage function is ~~plan.sh~~, it should have been `resource-quotas.sh`

**Comment by drsm79** [comment]
Good eyes, thanks - closed in #3
