### ISSUE TITLE
Azure-preflight script is reporting argument --subscription/-s: expected one argument

### ISSUE THREAD

**Issue by VinnieGrack** [EnterpriseDB/cloud-utilities#32]
Hiya Team, We got client onboarding for coming Tuesday, having issue with running the script. See the error details. Could you help me resolve this ASAP?

<img width="821" alt="image" src="https://user-images.githubusercontent.com/11228913/145216148-5519856d-ae9a-40dc-b4c7-ac694d112936.png">

**Comment by Simonzhaohui** [comment]
Hello @VinnieGrack 

Could you check the az CLI version ? There has [known issue](https://github.com/Azure/azure-cli/issues/20348) on az CLI 2.30.0.  We recommend to run preflight script using [cloudshell](https://portal.azure.com/#cloudshell/), or azure-cli (2.29.2 or 2.31.0).

**Comment by xugy99** [comment]
>  Could you check the azure-cli version 
this is something we can do to check in the azure-preflight.sh script and output to log.

**Comment by Simonzhaohui** [comment]
@xugy99, sure. I will add azure-cli version check in azure-preflight.sh.

**Comment by Simonzhaohui** [comment]
The issue has been fixed.
